// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: account.sql

package db

import (
	"context"
)

const getAllAccount = `-- name: GetAllAccount :many
SELECT id, username, email, password_hash, bio, profile_image, position, organisation, birthday FROM "account"
LIMIT $1
`

func (q *Queries) GetAllAccount(ctx context.Context, limit int32) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAllAccount, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Bio,
			&i.ProfileImage,
			&i.Position,
			&i.Organisation,
			&i.Birthday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
