// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	GetAllAccount(ctx context.Context, limit int32) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
